# Generated by Django 5.0.4 on 2024-05-02 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groceryitem',
            name='image',
            field=models.ImageField(blank=True, upload_to='grocery/images/'),
        ),
    ]
